### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by thomasverleye** [khalwat/minify#8]
Hi,

I had an error with your plugin in one of your vendors (tubalmartin). I had to change lin 769 to 771 with following code:
```
case 'M': case 'm': return (int) substr($size, 0, strlen($size) -1) * 1048576;
case 'K': case 'k': return (int) substr($size, 0, strlen($size) -1) * 1024;
case 'G': case 'g': return (int) substr($size, 0, strlen($size) -1) * 1073741824;
```
This happend because PHP 7.1 is strict with string & int convetions

Cheers!

**Comment by khalwat** [comment]
Ah interesting, okay thanks, I'll see if they have perhaps updated it upstream.

**Comment by khalwat** [comment]
When you get a chance, can you try out the version I just pushed to the `develop` branch? I updated all of the dependencies:

https://github.com/nystudio107/minify/tree/develop

**Comment by JonnyBR12** [comment]
Hey @khalwat 

Got the same issue after upgrading PHP version and tried the dev branch but no joy. Also tried adding the 3 lines from thomas still getting the error. Did you get a fix for this? Cheers.

**Comment by khalwat** [comment]
Okay guys, I checked in the change:

https://github.com/nystudio107/minify/tree/develop

I don't have a PHP 7.1 setup to test with, so let me know how this works out? If there are still errors, if you paste in the actual error with line number, etc., that'd be great!

**Comment by khalwat** [comment]
https://github.com/mrclay/minify/issues/580

**Comment by panrus** [comment]
```
case 'M': case 'm': return intval($size) * 1048576; 
case 'K': case 'k': return intval($size) * 1024; 
case 'G': case 'g': return intval($size) * 1073741824;
```

will be more suitable

**Comment by khalwat** [comment]
Changes made @panrus 

Can someone give this a whirl on a PHP 7.1 setup?

https://github.com/nystudio107/minify/tree/develop

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/minify/releases/tag/1.1.2
